lib/idopter_forum_web/router.ex
defmodule IdopterForumWeb.Router do
  use IdopterForumWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IdopterForumWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/threads", ThreadController do
      post "/comment", ThreadController, :add_comment
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", IdopterForumWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: IdopterForumWeb.Telemetry
    end
  end
end

lib/idopter_forum/forum/thread.ex
defmodule IdopterForum.Forum.Thread do
  use Ecto.Schema
  import Ecto.Changeset

  alias IdopterForum.Forum.Comment

  schema "threads" do
    field :author, :string
    field :description, :string
    field :title, :string

    timestamps()

    has_many :comments, Comment
  end

  @doc false
  def changeset(thread, attrs) do
    thread
    |> cast(attrs, [:title, :description, :author])
    |> validate_required([:title, :description, :author])
  end
end

lib/idopter_forum_web/controllers/thread_controller.ex
defmodule IdopterForumWeb.ThreadController do
  use IdopterForumWeb, :controller

  alias IdopterForum.Forum
  alias IdopterForum.Forum.{Comment, Thread}
  alias IdopterForum.Repo

  def index(conn, params) do
    {threads, kerosene} =
      Forum.list_threads()
      |> Repo.paginate(params)

    render(conn, "index.html", threads: threads, kerosene: kerosene)
  end

  def new(conn, _params) do
    changeset = Forum.change_thread(%Thread{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"thread" => thread_params}) do
    case Forum.create_thread(thread_params) do
      {:ok, thread} ->
        conn
        |> put_flash(:info, "Thread created successfully.")
        |> redirect(to: Routes.thread_path(conn, :show, thread))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    thread =
      Forum.get_thread!(id)
      |> Repo.preload([:comments])

    changeset = Comment.changeset(%Comment{}, %{})
    render(conn, "show.html", thread: thread, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    thread = Forum.get_thread!(id)
    changeset = Forum.change_thread(thread)
    render(conn, "edit.html", thread: thread, changeset: changeset)
  end

  def update(conn, %{"id" => id, "thread" => thread_params}) do
    thread = Forum.get_thread!(id)

    case Forum.update_thread(thread, thread_params) do
      {:ok, thread} ->
        conn
        |> put_flash(:info, "Thread updated successfully.")
        |> redirect(to: Routes.thread_path(conn, :show, thread))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", thread: thread, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    thread = Forum.get_thread!(id)
    {:ok, _thread} = Forum.delete_thread(thread)

    conn
    |> put_flash(:info, "Thread deleted successfully.")
    |> redirect(to: Routes.thread_path(conn, :index))
  end

  def add_comment(conn, %{"comment" => comment_params, "thread_id" => thread_id}) do
    thread = thread_id

    Forum.get_thread!(thread_id)
    |> Repo.preload([:comments])

    case Forum.add_comment(thread_id, comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes.thread_path(conn, :show, thread))

      {:error, _error} ->
        conn
        |> put_flash(:error, "Error while creating comment")
        |> redirect(to: Routes.thread_path(conn, :show, thread))
    end
  end
end

lib/idopter_forum_web/views/thread_view.ex
defmodule IdopterForumWeb.ThreadView do
  use IdopterForumWeb, :view
  import Kerosene.HTML
end

lib/idopter_forum_web/templates/thread/comment_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= textarea f, :text, placeholder: 'Here is a some text input', required: true %>
  <%= error_tag f, :text %>

  <%= text_input f, :author, placeholder: 'Your name', required: true %>
  <%= error_tag f, :author %>

  <div>
    <a class="waves-effect waves-light btn grey" href="/threads/"> Back </a>
    <button class="btn waves-effect waves-light grey" type="submit" name="action">Create</button>
  </div>
<% end %>

lib/idopter_forum_web/templates/thread/comment_index.html.eex
<div class="row">
  <div class="col s12">
    <%= for comment <- @comments do %>
      <h5 class="comment-title"><%= comment.author %>:</h5>
            <td><%= comment.text %></td>
    <% end %>
  </div>
</div>

lib/idopter_forum_web/templates/thread/edit.html.eex
<h1>Edit Thread</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.thread_path(@conn, :update, @thread)) %>

<span><%= link "Back", to: Routes.thread_path(@conn, :index) %></span>

lib/idopter_forum_web/templates/thread/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :title, placeholder: 'Title:', required: true %>
  <%= error_tag f, :title %>

  <%= textarea f, :description, placeholder: 'Here is a some text input', required: true %>
  <%= error_tag f, :description %>

  <div>
      <%= text_input f, :author, placeholder: 'Your name', required: true %>
      <%= error_tag f, :author %>

      <a class="waves-effect waves-light btn grey" href="/threads/"> Back </a>
      <button class="btn waves-effect waves-light grey" type="submit" name="action">Create</button>
  </div>
<% end %>

lib/idopter_forum_web/templates/thread/index.html.eex
<div class="row">
  <div class="col s9">
    <h3 class="forum-title">Forum</h3>
  </div>
  <div class="col s3 right-align">
    <a class="waves-effect waves-light btn grey" href="/threads/new"> New thread </a>
  </div>
</div>
<table class="highlight">
  <tbody>
    <%= for thread <- @threads do %>
      <tr>
        <td>
          <h5 class="thread-title"><%= thread.title %></h5>
        </td>
        <td class="right-align">
          <span><%= link "details", to: Routes.thread_path(@conn, :show, thread) %></span>
        </td>
        <td class="right-align">
          <%= Enum.count(thread.comments) %> replies
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @conn, @kerosene %>

lib/idopter_forum_web/templates/thread/new.html.eex
<h3 class="thread-title">New Thread</h3>

<%= render "form.html", Map.put(assigns, :action, Routes.thread_path(@conn, :create)) %>

lib/idopter_forum_web/templates/thread/show.html.eex
<div class="row valign-wrapper">
  <div class="col s4">
    <h3 class="thread-title"><%= @thread.title %></h3>
  </div>
  <div class="col s8">
    -
    <span class="thread-author"> <%= @thread.author %> </span>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <span class="grey-text"> <%= @thread.description %> </span>
  </div>
</div>

<hr class="solid">

<h4 class="thread-replies">Replies</h4>
<%= render "comment_index.html", comments: @thread.comments %>

<h4 class="thread-reply">Reply:</h4>
<%= render "comment_form.html", thread: @thread, changeset: @changeset, action: Routes.thread_thread_path(@conn, :add_comment, @thread) %>